---
- name: Create MinIO systemd service file from template
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart MinIO

- name: Reload systemd and start MinIO service
  ansible.builtin.systemd:
    name: minio
    daemon_reload: true
    enabled: true
    state: started
